version: '3.8'

services:
  web:
    image: devops-build  
    container_name: my-static-site-container
    ports:
      - "80:80"
    restart: always  
    environment:
      - NGINX_HOST=13.60.252.86
      - NGINX_PORT=80
